### ISSUE TITLE
Card Designs.

### ISSUE THREAD

**Issue by DLT-Africa** [DLT-Africa/DLT-Africa-Website#193]
Default display should show the filtered developers from the first button - Blockchain.
Card should be a grid of 3 cards for desktop size, 2 for tablet, 1 for mobile screen.
Each page should have a maximum card of 9 -- 3 rows, 3 columns.
Pagination

**Comment by ameer017** [comment]
Fill me in

**Comment by ameer017** [comment]
Completed
